# Generated by Django 4.2.14 on 2025-12-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_available',
        ),
        migrations.AddField(
            model_name='book',
            name='available_copies',
            field=models.IntegerField(default=1, help_text='Number of copies currently available for loan.'),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='total_copies',
            field=models.IntegerField(default=1, help_text='Total number of copies owned.'),
        ),
    ]
