# Generated by Django 4.2.14 on 2026-01-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0004_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom Complet')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('member_id', models.CharField(max_length=50, unique=True, verbose_name='ID Membre')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_loans', models.IntegerField(default=5, verbose_name='Nombre maximum de prêts')),
            ],
        ),
    ]
