# Generated by Django 4.2.14 on 2026-01-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0006_remove_loan_patron_loan_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='ID Membre'),
        ),
    ]
